=== GPUOpen-Archive/common-lib-amd-AMDTCpuPerfEventUtils-1.0/1.0/Data/Profiles/dcconfig.dtd
<!--
        Data collection (DC) configuration DTD
        Date: 15 March 2007
        Version: 1.2
        Copyright (c) 2006,2007 Advanced Micro Devices, Inc. All rights reserved.

        This DTD checks the validity of CodeAnalyst data collection
        configuration XML files.
 -->

  <!ELEMENT dc_configuration (tbp|ebp|sim|ibs)>

  <!ELEMENT tbp (tool_tip,description)>
  <!ATTLIST tbp name            CDATA #REQUIRED>
  <!ATTLIST tbp interval        CDATA "1.0">

  <!ELEMENT sim (tool_tip,description)>
  <!ATTLIST sim name            CDATA #REQUIRED>
  <!ATTLIST sim warmup_caches   CDATA "T">
  <!ATTLIST sim run_sim_after   CDATA "T">
  <!ATTLIST sim save_trace      CDATA "T">
  <!ATTLIST sim multiplier      CDATA "15">
  <!ATTLIST sim proc_core       CDATA "AMD Athlon64">
  <!ATTLIST sim max_to_trace    CDATA "5">
  <!ATTLIST sim trace_file_name CDATA "">

  <!ELEMENT ebp (group+,tool_tip,description)>
  <!ATTLIST ebp name            CDATA #REQUIRED>
  <!ATTLIST ebp mux_period      CDATA "1">
  <!ATTLIST ebp num_groups      CDATA #IMPLIED>

  <!ELEMENT ibs (tool_tip,description)>
  <!ATTLIST ibs name            CDATA #REQUIRED>
  <!ATTLIST ibs fetch_sampling  CDATA "T">
  <!ATTLIST ibs op_sampling     CDATA "T">
  <!ATTLIST ibs fetch_max_count CDATA "250000">
  <!ATTLIST ibs op_max_count    CDATA "250000">

  <!ELEMENT group (event+)>
  <!ATTLIST group valid         CDATA #IMPLIED>

  <!ELEMENT event EMPTY>
  <!ATTLIST event select       CDATA #REQUIRED>
  <!ATTLIST event mask         CDATA #REQUIRED>
  <!ATTLIST event os           CDATA #REQUIRED>
  <!ATTLIST event user         CDATA #REQUIRED>
  <!ATTLIST event count        CDATA #REQUIRED>
  <!ATTLIST event edge_detect  CDATA "F">

  <!ELEMENT tool_tip    (#PCDATA)>
  <!ELEMENT description (#PCDATA)>

=== GPUOpen-Archive/common-lib-amd-AMDTCpuPerfEventUtils-1.0/1.0/Data/Profiles/0x6/branch.xml
<?xml version="1.0"?>
<!DOCTYPE dc_configuration SYSTEM "dcconfig.dtd">

<!--     
         Analyze branch/near return prediction using event-based profiling
         Date:    3 May 2010
         Version: 1.2
         Processor: AMD K7 family
         Copyright (c) 2007-2010 Advanced Micro Devices, Inc. 
                       All rights reserved.
 -->

<dc_configuration>

  <ebp name="Investigate Branching" mux_period="0">

      <event select="C0" mask="00" os="T" user="T" count="250000"></event>
      <event select="C2" mask="00" os="T" user="T" count="25000"></event>
      <event select="C3" mask="00" os="T" user="T" count="25000"></event>
      <event select="C4" mask="00" os="T" user="T" count="25000"></event>

    <tool_tip>
      Find mispredicted branches
    </tool_tip>

    <description>
      Use this configuration to find poorly predicted branches.
    </description>

  </ebp>

</dc_configuration>
